### ISSUE TITLE
Kod nie działa i nie wiem dlaczego, pomocy !

### ISSUE THREAD

**Issue by Studniek** [korona-science/homework-Studniek#1]
Dodaję drugi raz, bo dodałem w złym repo

**Comment by RouNNdeL** [comment]
Masz problem z indentacją, wyrównaj linijki np z pomocą IDE lub [tego](https://codebeautify.org/python-formatter-beautifier) narzędzia

**Comment by RouNNdeL** [comment]
Testy przeszły
